# Site settings
description: ""
url: "" # with the https protocol
# enforce_ssl: www.ignaciodenuevo.com # without any protocol
email: 
twitter: 
github: 
baseurl: ""

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Pagination settings
paginate_path: /blog/page:num
paginate: 10

# Permalink
permalink: pretty

# Sass settings
sass:
  style: :compressed

# GEMS
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  